### ISSUE TITLE
This application is not working with C drive.

### ISSUE THREAD

**Issue by sandynit01** [bassemAgmi/EInvoicingSigner#24]
I have tried to use this in C Drive since i have only single drive. It is not working and expecting some library on D drive. 
Is it possible to have option to add Drive before execution and it will work on any drive.

**Comment by sandynit01** [comment]
I got below error while using this application from C drive.
Errors: 

Unhandled exception. Net.Pkcs11Interop.Common.UnmanagedException: Unable to load library. Error code: 0x0000007E. Error detail: The specified module could not be found.
   at Net.Pkcs11Interop.Common.UnmanagedLibrary.Load(String fileName)
   at Net.Pkcs11Interop.LowLevelAPI41.Pkcs11Library..ctor(String libraryPath)
   at Net.Pkcs11Interop.HighLevelAPI41.Pkcs11Library..ctor(Pkcs11InteropFactories factories, String libraryPath, AppType appType)
   at Net.Pkcs11Interop.HighLevelAPI41.Factories.Pkcs11LibraryFactory.LoadPkcs11Library(Pkcs11InteropFactories factories, String libraryPath, AppType appType)
   at Net.Pkcs11Interop.HighLevelAPI.Factories.Pkcs11LibraryFactory.LoadPkcs11Library(Pkcs11InteropFactories factories, String libraryPath, AppType appType)
   at TokenSigner.SignWithCMS(String serializedJson) in D:\work\Workspace\EInvoicingSigner\EInvoicingSigner\Signer.cs:line 113
   at TokenSigner.Main(String[] args) in D:\work\Workspace\EInvoicingSigner\EInvoicingSigner\Signer.cs:line 7

**Comment by socertis** [comment]
It seems like an error on package installation, but first try to point the environment to a specific folder rather than the default one, if it didn't work, then reinstall that package.
you can find it in the debugging options and also, you can refer to this [question.](https://stackoverflow.com/questions/14261439/how-to-change-directories-on-console-application)

**Comment by sandynit01** [comment]
Thanks for your reply. Application started working after token app is started.
