### ISSUE TITLE
how does it work?

### ISSUE THREAD

**Issue by Roulah** [bassemAgmi/EInvoicingSigner#3]
1- What do you mean by token PIN? is it the access token from login?
2- unhandled error was generated when running the exe with a valid json v0.9?

**Comment by MohamedYousof** [comment]
1- usb token pin is like a password, you will get it from token supplier and can be changed later.
2- change it to 1.0

**Comment by Roulah** [comment]
For the point 2 i already have the json as V1.0 before sending it to your bat file

**Comment by Roulah** [comment]
i removed the node documents from the begining and it worked!!
BUT the result json file FullSignedDocument.json, i have **Any** in the signature value as below?
"signatures": [
    {
      "signatureType": "I",
      "value": "ANY"
    }
  ]

**Comment by bassemAgmi** [comment]
Make sure you installed the software from token supplier.

**Comment by Roulah** [comment]
Thank you. you were right about installing the software.
But now the error changed into:
Unhandled exception. Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: An internal error occurred.
   at Internal.Cryptography.CngCommon.TrySignHash(SafeNCryptKeyHandle keyHandle, ReadOnlySpan`1 hash, Span`1 signature, AsymmetricPaddingMode paddingMode, Void* pPaddingInfo, Int32& bytesWritten)
   at System.Security.Cryptography.RSACng.TrySignHash(ReadOnlySpan`1 hash, Span`1 destination, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding, Int32& bytesWritten)
   at System.Security.Cryptography.Pkcs.CmsSignature.RSAPkcs1CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, String& signatureAlgorithm, Byte[]& signatureValue)
   at System.Security.Cryptography.Pkcs.CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, String& oid, ReadOnlyMemory`1& signatureValue)
   at System.Security.Cryptography.Pkcs.CmsSigner.Sign(ReadOnlyMemory`1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts)
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer, Boolean silent)
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer)
   at TokenSigner.SignWithCMS(String serializedJson)
   at TokenSigner.Main(String[] args)

**Comment by bassemAgmi** [comment]
Can you give some details about operating system version, it is a server or local machine, the current user privilege.

**Comment by Roulah** [comment]
It is on a windows 10 (local machine) and the flash is related to it. I tried to run the batch file (Run As Administrator) but it gave me the same error. I installed the runnable version on a separate New folder. Even the IT gave full access rights to the user logged in with no success.

**Comment by bassemAgmi** [comment]
Can you check the Windows Event Viewer under the category of “Application”.

**Comment by Roulah** [comment]
there were 2 error events:
**_Application Error:_**
Faulting application name: EInvoicingSigner.exe, version: 1.0.0.0, time stamp: 0x5fb3100b
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1348, time stamp: 0x76fcd692
Exception code: 0xe0434352
Fault offset: 0x0000000000034f69
Faulting process id: 0x36d0
Faulting application start time: 0x01d7dc8596cdcbea
Faulting application path: C:\EInvoice\publish\EInvoicingSigner.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 165d942b-21e0-4660-9e09-d49322d224fb
Faulting package full name: 
Faulting package-relative application ID: 

_**.Net Runtime Error:**_
Application: EInvoicingSigner.exe
CoreCLR Version: 4.700.20.47201
.NET Core Version: 3.1.9
Description: The process was terminated due to an unhandled exception.
Exception Info: Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: An internal error occurred.
   at Internal.Cryptography.CngCommon.TrySignHash(SafeNCryptKeyHandle keyHandle, ReadOnlySpan`1 hash, Span`1 signature, AsymmetricPaddingMode paddingMode, Void* pPaddingInfo, Int32& bytesWritten)
   at System.Security.Cryptography.RSACng.TrySignHash(ReadOnlySpan`1 hash, Span`1 destination, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding, Int32& bytesWritten)
   at System.Security.Cryptography.Pkcs.CmsSignature.RSAPkcs1CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, String& signatureAlgorithm, Byte[]& signatureValue)
   at System.Security.Cryptography.Pkcs.CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, String& oid, ReadOnlyMemory`1& signatureValue)
   at System.Security.Cryptography.Pkcs.CmsSigner.Sign(ReadOnlyMemory`1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts)
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer, Boolean silent)
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer)
   at TokenSigner.SignWithCMS(String serializedJson)
   at TokenSigner.Main(String[] args)

**Comment by bassemAgmi** [comment]
We have a recommended fix. To check the recommended fix, please update the publish folder by https://github.com/bassemAgmi/EInvoicingSigner/blob/master/publishUpdatedFile.rar . If is it ok, please tell us to commit the change.

**Comment by Roulah** [comment]
Hi, it did not work. still the same error

**Comment by melamrey** [comment]
hi have the the same problem on the  i try cms.ComputeSignature(signer);
and  cms.ComputeSignature(signer, false);
but still the same problem
Unhandled exception. Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: An internal error occurred.
   at Internal.Cryptography.CngCommon.TrySignHash(SafeNCryptKeyHandle keyHandle, ReadOnlySpan`1 hash, Span`1 signature, AsymmetricPaddingMode paddingMode, Void* pPaddingInfo, Int32& bytesWritten)
   at System.Security.Cryptography.RSACng.TrySignHash(ReadOnlySpan`1 hash, Span`1 destination, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding, Int32& bytesWritten)
   at System.Security.Cryptography.Pkcs.CmsSignature.RSAPkcs1CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, String& signatureAlgorithm, Byte[]& signatureValue)
   at System.Security.Cryptography.Pkcs.CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, String& oid, ReadOnlyMemory`1& signatureValue)
   at System.Security.Cryptography.Pkcs.CmsSigner.Sign(ReadOnlyMemory`1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts)
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer, Boolean silent)
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer)
   at TokenSigner.SignWithCMS(String serializedJson) in C:\Users\Mohamed\Documents\EInvoicingSigner-da969681a5a599557c1998f992ec64f1bd9eea79\EInvoicingSigner-da969681a5a599557c1998f992ec64f1bd9eea79\EInvoicingSigner\Signer.cs:line 154
   at TokenSigner.Main(String[] args) in C:\Users\Mohamed\Documents\EInvoicingSigner-da969681a5a599557c1998f992ec64f1bd9eea79\EInvoicingSigner-da969681a5a599557c1998f992ec64f1bd9eea79\EInvoicingSigner\Signer.cs:line 48

**Comment by melamrey** [comment]
i was have this  problem 
the problem in epass2003 driver change the version you use 
 download anothet one
