### ISSUE TITLE
Unable to load library "eps2003csp11.dll"

### ISSUE THREAD

**Issue by AhmedHemdan21** [bassemAgmi/EInvoicingSigner#30]
Whenever I try to run the application or the runtime version, I always get the following error:
```

D:\EInvoicing>D:\EInvoicing\publish/EInvoicingSigner.exe  D:\EInvoicing 999999 "Egypt Trust Sealing CA"
First argument D:\EInvoicing
Second argument 999999
Third argument Egypt Trust Sealing CA
Unhandled exception. Net.Pkcs11Interop.Common.UnmanagedException: Unable to load library. Error code: 0x0000007E. Error detail: The specified module could not be found.
   at Net.Pkcs11Interop.Common.UnmanagedLibrary.Load(String fileName)
   at Net.Pkcs11Interop.LowLevelAPI41.Pkcs11Library..ctor(String libraryPath)
   at Net.Pkcs11Interop.HighLevelAPI41.Pkcs11Library..ctor(Pkcs11InteropFactories factories, String libraryPath, AppType appType)
   at Net.Pkcs11Interop.HighLevelAPI41.Factories.Pkcs11LibraryFactory.LoadPkcs11Library(Pkcs11InteropFactories factories, String libraryPath, AppType appType)
   at Net.Pkcs11Interop.HighLevelAPI.Factories.Pkcs11LibraryFactory.LoadPkcs11Library(Pkcs11InteropFactories factories, String libraryPath, AppType appType)
   at TokenSigner.SignWithCMS(String serializedJson) in D:\work\Workspace\EInvoicingSigner\EInvoicingSigner\Signer.cs:line 113
   at TokenSigner.Main(String[] args) in D:\work\Workspace\EInvoicingSigner\EInvoicingSigner\Signer.cs:line 76

D:\EInvoicing>PAUSE

```
Environment: 
Windows 11

any suggestions?

**Comment by AhmedHemdan21** [comment]
Downloading the `"eps2003csp11.dll"` file from the internet, adding it to the project, and configuring the project to x86 has resolved that issue.

currently, the application doesn't load `pkcs11Library` slots

**Comment by BothienaAdel** [comment]
please,where you added the "eps2003csp11.dll" in the project ? Did you add it to Bin Folder ?
do you change the DllLibPath?

**Comment by AhmedHemdan21** [comment]
@BothienaAdel yes in the bin folder, add it to your project and change file properties to be always copy

**Comment by BothienaAdel** [comment]
thanks for replaying 
it reads the signature locally only but after publish for cloud customers it can't read the signature it gives me no slots found

**Comment by AhmedHemdan21** [comment]
@BothienaAdel actually I'm facing the slots issue until now locally, still, I didn't make it to deployment, 
could you please guide me through how did you make it work locally, did you need to plug in the USB key or how did it work for you?

**Comment by BothienaAdel** [comment]
install epass2003 from egypt trust then insert USB to your device after that login with the key through epass2003 and install the certificate,you need to insert the USB to your device and insert its Bin to your webservice to read it locally

**Comment by MaxBayne** [comment]
انا محتاج افهم نقطة جميع اكواد التوقيع المتوفرة علي الانترنت كلها بتبحث عن شهادة بالاسم
Egypt Trust Sealing CA
الموجودة في Person  و CurrentUser
السؤال هل المطلوب للتوقيع الشهادة دي Egypt Trust Sealing CA والا الشهادة المتوفرة داخل التوكن الا بتيجي باسم العميل
مع العلم اني لو حاولت اني اسطب الشهادة الخاصة بالعميل الموجودة داخل التوكن واسطبها داخل Person  و CurrentUser
بتتسطب ولكن بدون Private Key والمطلوب اساسي في عملية التوقيع

@BothienaAdel BothienaAdel
@bassemAgmi

**Comment by menams2010** [comment]
> انا محتاج افهم نقطة جميع اكواد التوقيع المتوفرة علي الانترنت كلها بتبحث عن شهادة بالاسم Egypt Trust Sealing CA الموجودة في Person و CurrentUser السؤال هل المطلوب للتوقيع الشهادة دي Egypt Trust Sealing CA والا الشهادة المتوفرة داخل التوكن الا بتيجي باسم العميل مع العلم اني لو حاولت اني اسطب الشهادة الخاصة بالعميل الموجودة داخل التوكن واسطبها داخل Person و CurrentUser بتتسطب ولكن بدون Private Key والمطلوب اساسي في عملية التوقيع
> 
> [@BothienaAdel](https://github.com/BothienaAdel) BothienaAdel [@bassemAgmi](https://github.com/bassemAgmi)

ممكن تبحث بسيريال الشهادة وده افضل لانها تروح علي اليوزر اول ما التوكن يعمل login
